# Shared Constants for SecureGrid

ALL_DEVICE_STATUSES = ["ACTIVE", "SUSPICIOUS", "QUARANTINED", "OFFLINE"]
DEVICE_STATUS_ACTIVE = "ACTIVE"
DEVICE_STATUS_QUARANTINED = "QUARANTINED"

ALL_SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

TRUST_STATUS_TRUSTED = "TRUSTED"
TRUST_STATUS_ELEVATED_RISK = "ELEVATED_RISK"
TRUST_STATUS_COMPROMISED = "COMPROMISED"

VOLTAGE_MIN_V = 100.0
VOLTAGE_MAX_V = 500.0
VOLTAGE_NOMINAL_V = 220.0

POWER_MIN_KW = 0.0
POWER_MAX_KW = 100.0

CURRENT_MIN_A = 0.0
CURRENT_MAX_A = 200.0

REQUEST_RATE_MAX_HZ = 50.0
